name: llm-phishing
channels:
 - defaults
 - conda-forge

dependencies:
  - python>=3.9
  - pip
  - openai
  - python-dotenv
  - ipykernel
  - jupyter
  - pandas
  - gradio
  - vcrpy
  - pytest
  - scikit-learn
  - xgboost
  - joblib
  - unittest
  - whois
  - pyopenssl
  - tqdm

